version: '3.7'

services:
  run-up-auth:
    container_name: run-up-strava
    build: .
    command: yarn start
    environment:
      PORT: 80
      VIRTUAL_HOST: strava.zorp.co
      STRAVA_CLIENT_URL: http://strava.zorp.co
      STRAVA_URL: https://www.strava.com
    expose:
      - 80
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy
