version: '3.7'

services:
  run-up-auth:
    container_name: run-up-auth
    build: .
    command: yarn start
    environment:
      PORT: 80
      STRAVA_CLIENT_URL: https://auth.zorp.co
      STRAVA_URL: https://www.strava.com
      VIRTUAL_HOST: auth.zorp.co
      LETSENCRYPT_HOST: auth.zorp.co
      LETSENCRYPT_EMAIL: hello@jackallen.me
    expose:
      - 80
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy
